[package]
name = "continuous-vesting"
version = "0.1.0"
edition = "2021"

[dependencies]
chia-protocol = "0.17.0"
chia-wallet-sdk = "0.20.0"
clvm-traits = { version = "0.17.0", features = ["derive"] }
clvm-utils = "0.17.0"
hex-literal = "0.4.1"
