# Special thanks to Rigidity
# https://github.com/xch-dev/chia-wallet-sdk/blob/main/.github/workflows/rust.yml
name: Rust
on:
  push:
    branches:
      - master
    tags:
      - "**"

  pull_request:
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cargo binstall
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      - name: Install thing
      - run: apt update && apt-get install -y libgtk-3-dev

      - name: Instal cargo-workspaces
        run: cargo binstall cargo-workspaces --locked -y

      - name: Install cargo-tarpaulin
        run: cargo binstall cargo-tarpaulin --locked -y

      - name: Run tests
        run: cargo tarpaulin --workspace --all-features --out xml

      - name: Cleanup coverage reports
        run: rm -f cobertura.xml

      - name: Clippy
        run: cargo clippy --workspace --all-features --all-targets

      - name: Fmt
        run: cargo fmt --all -- --files-with-diff --check
